// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Jwtkey struct {
	ID         int64              `json:"id"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	Algorithm  string             `json:"algorithm"`
	IsActive   pgtype.Bool        `json:"is_active"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID                    int64              `json:"id"`
	UserID                int64              `json:"user_id"`
	Token                 string             `json:"token"`
	RefreshToken          string             `json:"refresh_token"`
	TokenExpiresAt        pgtype.Timestamptz `json:"token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	IsActive              pgtype.Bool        `json:"is_active"`
	Ip                    pgtype.Text        `json:"ip"`
	UserAgent             pgtype.Text        `json:"user_agent"`
	LoggedOut             pgtype.Timestamptz `json:"logged_out"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             int64              `json:"id"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	EmailVerified  bool               `json:"email_verified"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type VerificationCode struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsUsed    bool               `json:"is_used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
